<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ifml" nsURI="http://www.omg.org/spec/IFML" nsPrefix="ifml">
  <eSubpackages name="extensions" nsURI="http://www.omg.org/spec/IFML/ext" nsPrefix="ext">
    <eClassifiers xsi:type="ecore:EClass" name="Form" eSuperTypes="#//core/ViewComponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="submitEvent" ordered="false"
          upperBound="-1" eType="#//extensions/SubmitEvent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Field" abstract="true" eSuperTypes="#//core/ViewComponentPart"/>
    <eClassifiers xsi:type="ecore:EClass" name="SelectionField" eSuperTypes="#//extensions/Field">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMultiSelection" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValidationRule" eSuperTypes="#//core/Constraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="Slot" eSuperTypes="#//core/ViewComponentPart">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//core/Parameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SortAttribute">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" ordered="false"
          lowerBound="1" eType="#//extensions/SortOrderEnum"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SelectEvent" eSuperTypes="#//core/ViewElementEvent"/>
    <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="#//core/ViewComponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="selectEvent" ordered="false"
          upperBound="-1" eType="#//extensions/SelectEvent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="submitEvent" upperBound="-1"
          eType="#//extensions/SubmitEvent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleField" eSuperTypes="#//extensions/Field"/>
    <eClassifiers xsi:type="ecore:EClass" name="SubmitEvent" eSuperTypes="#//core/ViewElementEvent"/>
    <eClassifiers xsi:type="ecore:EClass" name="Selector" eSuperTypes="#//core/Expression #//core/ViewComponentPart"/>
    <eClassifiers xsi:type="ecore:EEnum" name="SortOrderEnum">
      <eLiterals name="ascending"/>
      <eLiterals name="descending"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Device" eSuperTypes="#//core/ContextDimension"/>
    <eClassifiers xsi:type="ecore:EClass" name="Position" eSuperTypes="#//core/ContextDimension"/>
    <eClassifiers xsi:type="ecore:EClass" name="UserRole" eSuperTypes="#//core/ContextDimension"/>
    <eClassifiers xsi:type="ecore:EClass" name="Details" eSuperTypes="#//core/ViewComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="Window" eSuperTypes="#//core/ViewContainer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isModal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNew" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="#//core/ViewElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="align" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="#//core/ViewElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ButtonText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Align" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextField" eSuperTypes="#//core/ViewElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="FontSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="TextFieldText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="core" nsURI="http://www.omg.org/spec/IFML/core" nsPrefix="core">
    <eClassifiers xsi:type="ecore:EClass" name="ViewPoint" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interactionFlowModelElements"
          ordered="false" upperBound="-1" eType="#//core/InteractionFlowModelElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
          eType="#//core/Context"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InteractionFlowElement" abstract="true"
        eSuperTypes="#//core/NamedElement #//core/InteractionFlowModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" ordered="false"
          upperBound="-1" eType="#//core/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inInteractionFlows" ordered="false"
          upperBound="-1" eType="#//core/InteractionFlow"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outInteractionFlows"
          ordered="false" upperBound="-1" eType="#//core/InteractionFlow" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NavigationFlow" eSuperTypes="#//core/InteractionFlow">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataFlows" ordered="false"
          upperBound="-1" eType="#//core/DataFlow"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActionEvent" eSuperTypes="#//core/Event"/>
    <eClassifiers xsi:type="ecore:EClass" name="InteractionFlowModel" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interactionFlowModelElements"
          ordered="false" upperBound="-1" eType="#//core/InteractionFlowModelElement"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterBindingGroup" eSuperTypes="#//core/InteractionFlowModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterBindings" ordered="false"
          upperBound="-1" eType="#//core/ParameterBinding" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterBinding" eSuperTypes="#//core/InteractionFlowModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceParameter" ordered="false"
          lowerBound="1" eType="#//core/Parameter"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetParameter" ordered="false"
          lowerBound="1" eType="#//core/Parameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContentModel" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="ecore:EClass UML.ecore#//Element"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ViewElement" eSuperTypes="#//core/InteractionFlowElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="viewElementEvents" ordered="false"
          upperBound="-1" eType="#//core/ViewElementEvent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activationExpression"
          ordered="false" eType="#//core/ActivationExpression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="viewContainer" eType="#//core/ViewContainer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//core/InteractionFlowElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="actionEvents" ordered="false"
          upperBound="-1" eType="#//core/ActionEvent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicBehavior" eType="#//core/DynamicBehavior"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" ordered="false"
          upperBound="-1" eType="#//core/Constraint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" ordered="false"
          upperBound="-1" eType="#//core/Annotation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DynamicBehavior" eSuperTypes="#//core/ContentBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="behavioralFeatureConcept"
          eType="#//core/BehavioralFeatureConcept"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="behaviorConcept" eType="#//core/BehaviorConcept"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataFlow" eSuperTypes="#//core/InteractionFlow"/>
    <eClassifiers xsi:type="ecore:EClass" name="InteractionFlow" abstract="true" eSuperTypes="#//core/InteractionFlowModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="srcInteractionFlowElement"
          ordered="false" lowerBound="1" eType="#//core/InteractionFlowElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="trgtInteractionFlowElement"
          ordered="false" lowerBound="1" eType="#//core/InteractionFlowElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterBindingGroup"
          ordered="false" eType="#//core/ParameterBindingGroup" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ViewElementEvent" eSuperTypes="#//core/Event"/>
    <eClassifiers xsi:type="ecore:EClass" name="InteractionFlowModelElement" abstract="true"
        eSuperTypes="#//core/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//core/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalEvent" eSuperTypes="#//core/Event"/>
    <eClassifiers xsi:type="ecore:EClass" name="Constraint" eSuperTypes="#//core/BooleanExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="ViewComponentPart" eSuperTypes="#//core/InteractionFlowElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="viewElementEvents" ordered="false"
          upperBound="-1" eType="#//core/ViewElementEvent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activationExpression"
          ordered="false" eType="#//core/ActivationExpression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subViewComponentParts"
          upperBound="-1" eType="#//core/ViewComponentPart" eOpposite="#//core/ViewComponentPart/parentViewComponentPart"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentViewComponentPart"
          lowerBound="1" eType="#//core/ViewComponentPart" eOpposite="#//core/ViewComponentPart/subViewComponentParts"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ViewContainer" eSuperTypes="#//core/ViewElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLandMark" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDefault" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="viewElements" ordered="false"
          upperBound="-1" eType="#//core/ViewElement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isXor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IFMLModel" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interactionFlowModel"
          ordered="false" lowerBound="1" eType="#//core/InteractionFlowModel" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contentModel" ordered="false"
          lowerBound="1" eType="#//core/ContentModel" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interactionFlowModelViewPoints"
          ordered="false" upperBound="-1" eType="#//core/ViewPoint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="domainModel" lowerBound="1"
          eType="#//core/DomainModel" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//core/InteractionFlowElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activationExpression"
          ordered="false" eType="#//core/ActivationExpression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="navigationFlows" ordered="false"
          upperBound="-1" eType="#//core/NavigationFlow" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interactionFlowExpression"
          ordered="false" eType="#//core/InteractionFlowExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContentBinding" abstract="true" eSuperTypes="#//core/ViewComponentPart">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniformResourceIdentifier"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InteractionFlowExpression" eSuperTypes="#//core/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interactionFlows" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//core/InteractionFlow"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataBinding" eSuperTypes="#//core/ContentBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="conditionalExpression"
          upperBound="-1" eType="#//core/ConditionalExpression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="visualizationAttributes"
          upperBound="-1" eType="#//core/VisualizationAttribute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="domainConcept" lowerBound="1"
          eType="#//core/DomainConcept"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ViewComponent" eSuperTypes="#//core/ViewElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="viewComponentParts" upperBound="-1"
          eType="#//core/ViewComponentPart" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SystemEvent" eSuperTypes="#//core/Event">
      <eStructuralFeatures xsi:type="ecore:EReference" name="triggeringExpressions"
          ordered="false" lowerBound="1" upperBound="-1" eType="#//core/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false"
          lowerBound="1" eType="#//core/SystemEventTypeEnum"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression" eSuperTypes="#//core/Expression"/>
    <eClassifiers xsi:type="ecore:EClass" name="ActivationExpression" eSuperTypes="#//core/BooleanExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//core/InteractionFlowModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//core/InteractionFlowModelElement #//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false"
          lowerBound="1" eType="#//core/ParameterKind" defaultValueLiteral="ordinary"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SystemEventTypeEnum">
      <eLiterals name="time"/>
      <eLiterals name="specialCondition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConditionalExpression" eSuperTypes="#//core/Expression #//core/ViewComponentPart"/>
    <eClassifiers xsi:type="ecore:EClass" name="Context" eSuperTypes="#//core/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="contextDimensions" upperBound="-1"
          eType="#//core/ContextDimension"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContextDimension" eSuperTypes="#//core/NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="VisualizationAttribute" eSuperTypes="#//core/ViewComponentPart">
      <eStructuralFeatures xsi:type="ecore:EReference" name="featureConcept" lowerBound="1"
          eType="#//core/FeatureConcept"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ParameterKind">
      <eLiterals name="ordinary" literal="ordinary"/>
      <eLiterals name="input" literal="input"/>
      <eLiterals name="output" literal="output"/>
      <eLiterals name="input_output" literal="input_output"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//core/InteractionFlowModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputPorts" lowerBound="1"
          upperBound="-1" eType="#//core/Port"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outputPorts" lowerBound="1"
          upperBound="-1" eType="#//core/Port"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interactionFlowModelElements"
          lowerBound="1" upperBound="-1" eType="#//core/InteractionFlowModelElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="#//core/InteractionFlowElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Annotation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureConcept" eSuperTypes="#//core/DomainElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="visualizationAttribute"
          eType="#//core/VisualizationAttribute"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DomainModel" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#//core/DomainElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DomainElement" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="domainModel" lowerBound="1"
          eType="#//core/DomainModel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLStructuralFeature" eSuperTypes="#//core/FeatureConcept">
      <eStructuralFeatures xsi:type="ecore:EReference" name="structuralFeature" eType="ecore:EClass UML.ecore#//StructuralFeature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DomainConcept" eSuperTypes="#//core/DomainElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataBinding" eType="#//core/DataBinding"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLDomainConcept" eSuperTypes="#//core/DomainConcept">
      <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" eType="ecore:EClass UML.ecore#//Classifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehavioralFeatureConcept" eSuperTypes="#//core/DomainElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicBehavior" eType="#//core/DynamicBehavior"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLBehavioralFeature" eSuperTypes="#//core/BehavioralFeatureConcept">
      <eStructuralFeatures xsi:type="ecore:EReference" name="behavioralFeature" eType="ecore:EClass UML.ecore#//BehavioralFeature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehaviorConcept" eSuperTypes="#//core/DomainElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicBehavior" eType="#//core/DynamicBehavior"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLBehavior" eSuperTypes="#//core/BehaviorConcept">
      <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" eType="ecore:EClass UML.ecore#//Behavior"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
